#You may full CICD workflow under*/
#Create a GitHub Repository:

#1.First, create a repository in GitHub to store your PL/SQL code, repository name is plsql-product-management.
#2. PL/SQL Code: ProductManager.sql script for managing products.

#File: ProductManager.sql

CREATE OR REPLACE PROCEDURE update_product_quantity ( p_product_id IN NUMBER, p_quantity IN NUMBER) AS
  BEGIN
    UPDATE Products
    SET Book_Quantity = p_quantity
    WHERE Product_ID = p_product_id;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END update_product_quantity;

#3. Commit and Push to GitHub:

git add ProductManager.sql
git commit -m "Added procedure to update product quantity";
git push origin main

#4. Set Up CI / CD with GitHub Actions:
  
#Create a .github/workflows/cicd.yml file 

name: PL/SQL CICD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Oracle Client
      run: |
        sudo apt-get update
        sudo apt-get install -y oracle-instantclient19.8-basic

    - name: Run PL/SQL Tests
      run: |
        sqlplus username/password@hostname:port/SID <<EOF
        @ProductManager.sql
        EXIT;
        EOF

    - name: Deploy PL/SQL Code
      run: |
        sqlplus username/password@hostname:port/SID <<EOF
        @ProductManager.sql
        EXIT;
        EOF

